export const scaleFactor = 4;

export const dialogueData = {
  pc: `This is my work station. I've been working primarily in the SaaS Support sphere since 2016. However, as of VERY recently, I've begun learning how to program my own video games. I'm self-taught with no formal education, so please excuse the mess if you review my code as I'm FAR better at editing/troubleshooting/QAing code than I am actually creating from sceatch! Here is a link to my <a href="https://github.com/geoffhenao" target="_blank">Github</a> if you'd like to review my code and/or other projects!`,
  degree: `This is my degree. Believe it or not, I majored in English with a concentration in Cultural, Media, and Rhetoric Studies. My first true passion is analyzing and breaking down complex themes/elements in media and contextualizing it for various audiences. One day, I might write The Next Great American Novel or an indie comic, but for now, I'm enjoying Product/Technical Support. You can check out a collection of my written work (from 2010 - 2019) <a href="https://geoffhenao.wordpress.com" target="_blank">here</a>!`,
  tv: `I don't watch too much TV nowadays, but when I do, it's usually basketball (Go Bulls!), pro wrestling (NJPW and AEW specifically), or catching up on an anime I'll inevitably decide I don't like a few months later.`,
  isamar: `Here's a painting done by my friend, Isamar Medina (fka Kawaii Suga). We've collaborated on several projects together, including the Slaps! Show, which established a platform for rising, independent artists to display their unconventional art in a gallery setting; additionally, we kept the price point for sales low, allowing new art buyers to purchase pieces from both new artists and established, well-known artists. As a whole, the Slaps! Show was a subversion of both art viewing and art purchasing, and have been my favorite experiences in the art world. Check out Isamar's website <a href="https://kawaiisuga.com" target="_blank">here</a>. Warning: It's NSFW!`,
  window: `Outside this window is my hometown, Chicago. As a native Chicagoan of 35+ years, there's nothing more I'd rather see outside my window than a crisp, Chicago sunset... except maybe a crisp, Japanese sunset.`,
  fridge: `My fridge usually consists of nothing but almond milk, frozen pizza, and gummy popsicles (they're so good). There was a point in recent life where I was a Pasta Papa, but those days are behind me for now.`,
  binterman: `This is my cat, Binterman (AKA Bints AKA Baba AKA Baba Cat AKA The Cutest F***ing Cat in the Whole F***ing World™). As of this writing (February 2025), he's 5 years old and as rambunctious as ever... maybe TOO rambunctious. Give him a follow on <a href="https://instagram.com/binterman" target="_blank">Instagram</a>!`,
  "couch-table": `While I don't watch that much TV anymore, I've been an avid gamer for 35+ years (I'm old). I primarily play JRPGs, but I do like the occasional horror and online shooter. Who knows, maybe I'll find motivation enough to program my own PlayStation game?`,
  resume: `This is my desk, and on it is my resume. I have over 10+ years of online content creation (primarily features, interviews, reviews, and news articles), nearly 10+ years of Product/Technical Support for SaaS companies, 5+ years of event photography (festivals, concerts, sporting events), and 3+ years of online marketing (namely setup/configuration/reporting of Google Analytics and Google Tag Manager). You can learn more about my work experience over on my <a href="https://www.linkedin.com/in/geoffhenao/" target="_blank">LinkedIn</a>.`,
  portfolio: `This project was made with Kaboom.js (which is a library for making games in JavaScript), and the text is rendered completely with HTML/CSS. The spritesheet was acquired online and slightly modified. You can also build a portfolio like this by checking out the JS Legend Dev video <a href="http://youtube.com/watch?v=zxbdPPrLL6A&t=138s" target="_blank">here</a>.`,
  bookshelf: `My bookshelf is mostly made up of gachapon, goshuincho, and other gadgets. There may or may not also be a Sonic the Hedgehog shrine displayed here...`,
  exit: `Leaving so soon? Thanks for stopping by! You can close this tab to exit.`,
};