export const scaleFactor = 4;

export const dialogueData = {
  pc: `This is my work station. I've been working primarily in the SaaS Support sphere since 2016. However, as of VERY recently, I've begun learning how to program my own video games. I'm self-taught with no formal guidance, so please excuse the mess if you review my code as I'm FAR better at editing/troubleshooting/QAing! Here is a link to my <a href="https://github.com/geoffhenao" target="_blank">Github</a> if you'd like to check out my projects!`,
  degree: `This is my degree. Believe it or not, I majored in English with a concentration in Cultural, Media, and Rhetoric Studies. My first true passion is analyzing and breaking down complex themes/elements in media and contextualizing it for various audiences. One day, I might write The Next Great American Novel or an indie comic, but for now, I'm enjoying Product/Technical Support. You can check out a collection of my favorite features, reviews, and interviews from 2010 - 2019 <a href="https://geoffhenao.wordpress.com" target="_blank">here</a>!`,
  tv: `As a former film journalist, I've spent far too much time analyzing and criticizing media. I don't watch too much TV nowadays, but when I do, it's usually YouTube (specifically travel vlogs in Japan), pro wrestling (AEW, NJPW, TJPW, and Stardom specifically), or pretending the Bulls will be good next season.`,
  isamar: `Here's a painting done by my friend, Isamar Medina (fka Kawaii Suga). We've collaborated on several projects together, including the Slaps! Show, which established a platform for rising, independent artists to display their unconventional art in a gallery setting; additionally, we kept the price point for sales low, allowing new art buyers to purchase pieces from both new artists and established, well-known artists. As a whole, the Slaps! Show was a subversion of both art viewing and art purchasing, and have been my favorite experiences in the art world. Check out Isamar's website <a href="https://kawaiisuga.com" target="_blank">here</a>. Warning: It's NSFW!`,
  chicago: `As a native Chicagoan of 35+ years, there's nothing more I'd rather see outside my window than a crisp, Chicago sunset... except maybe a crisp, Japanese sunset.`,
  binterman: `This is my cat, Binterman (AKA Bints AKA Baba AKA Baba Cat AKA The Cutest F***ing Cat in the Whole F***ing World™). As of this writing (February 2025), he's 5 years old and as rambunctious as ever, but nobody puts Baba in a corner. Give him a follow on <a href="https://instagram.com/binterman" target="_blank">Instagram</a>!`,
  couch: `While I don't watch that much TV anymore, I've been an avid gamer for 95% of my life. I primarily play JRPGs, but I do like the occasional horror and online shooter. Who knows, maybe I'll find motivation enough to program my own PlayStation game?`,
  resume: `Thank you for taking the time to check my gamified portfolio out. I wanted to make this project as a proof of concept to show hiring managers that I'm a quick learner (I have no formal education with coding!), incredibly adaptable (using the tutorial as a base, I've made numerous iterations since the game originally launched on 2.13.25), and technologically curious. I hope you enjoy getting to learn more about me!`,
  geoff: `Welcome to my gamified portfolio! I have over 10+ years of online content creation (primarily features, interviews, reviews, photography, and news articles), nearly 10+ years of Product/Technical Support for SaaS companies, 5+ years of event photography (festivals, concerts, sporting events), 5+ years of event coordination (including but not limited to Slaps! Show and Midwest Ska Fest), and 3+ years of online marketing (namely setup/configuration/reporting of Google Analytics and Google Tag Manager). You can learn more about my work experience over on my <a href="https://www.linkedin.com/in/geoffhenao/" target="_blank">LinkedIn</a>.`,
  ska: `Whoa, a ska flag in 2025? Since high school, I've been helping coordinate and market concerts with my friends. We used to run an annual summer ska festival, Midwest Ska Fest (MWSF), and I served as the Business Coordinator sourcing sponsorships and partnerships. Some brands I've worked with via MWSF include Dark Matter Coffee, Threadless, Revolution Brewing, and more!`,
  bookshelf: `My bookshelf is mostly made up of gachapon, goshuincho, and other gadgets. There may or may not also be a Sonic the Hedgehog shrine displayed here...`,
  japan: `This is a banzuke, which is basically a ranked list of sumo wrestlers that participated in last May's sumo tournament. I try to travel to Japan at least once a year, but last May was my first time seeing sumo!`,
  exit: `Leaving so soon? Thanks for stopping by! Don't forget to check out my <a href="https://www.linkedin.com/in/geoffhenao/" target="_blank">LinkedIn</a> on your way out.`,
};